"""empty message

Revision ID: 0f01924d641c
Revises: ffc70a6647b4
Create Date: 2020-10-22 16:34:56.204338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f01924d641c'
down_revision = 'ffc70a6647b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('phase', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False)
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lunar_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lunar_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lunar_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunar_month')
    op.drop_table('day')
    op.drop_index(op.f('ix_phases_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_table('lunar_event')
    # ### end Alembic commands ###
