"""empty message

Revision ID: 15bf5d7cad1e
Revises: ffc70a6647b4
Create Date: 2020-10-19 17:17:14.330970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bf5d7cad1e'
down_revision = 'ffc70a6647b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
